name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: BiancaMichelle
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Show output folder (debug)
        run: ls -la dist

      - name: Publish snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
