name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Corre una vez por día
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generar snake.svg con Platane/snk
        uses: Platane/snk@master
        with:
          github_user_name: BiancaMichelle
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Publicar en GitHub Pages (rama output)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
